Update firstAction.yml

diff --git a/.github/workflows/firstAction.yml b/.github/workflows/firstAction.yml
--- a/.github/workflows/firstAction.yml
+++ b/.github/workflows/firstAction.yml
@@ -41,8 +41,7 @@ jobs:
       
       # Runs my check bash script
       - name: Run Check
+        if: $( ./check.sh )
         run: |
-          if [[ $( ./check.sh ) ]]
-          then
-            echo '::error file={check.sh},line={1},endLine={1},title={Check Failed}::{The Check script returned a Fail message}'
-          fi
+          echo '::error file={check.sh},line={1},endLine={1},title={Check Failed}::{The Check script returned a Fail message}'
+          exit 1
