Update firstAction.yml

diff --git a/.github/workflows/firstAction.yml b/.github/workflows/firstAction.yml
--- a/.github/workflows/firstAction.yml
+++ b/.github/workflows/firstAction.yml
@@ -41,7 +41,9 @@ jobs:
       
       # Runs my check bash script
       - name: Run Check
-        if: ${{ ./check.sh }}
         run: |
-          echo '::error file={check.sh},line={1},endLine={1},title={Check Failed}::{The Check script returned a Fail message}'
-          exit 1
+          if [[ $( ./check.sh ) ]]
+          then
+            echo '::error file={check.sh},line={1},endLine={1},title={Check Failed}::{The Check script returned a Fail message}'
+            exit 1
+          fi
